[package]

authors = ["Mesocarp"]
description = "Multi-agent coordination framework in Rust with single and multi-threaded execution engines."
edition = "2021"
homepage = "https://github.com/TheMesocarp/aika"
keywords = [
  "multi-agent",
  "simulation",
  "coordination",
  "synchronization",
  "time-warp",
]
license = "LGPL-2.1"
name = "aika"
readme = "README.md"
repository = "https://github.com/TheMesocarp/aika"
version = "0.2.0"


[profile.release]
opt-level = 3

[features]

[dependencies]
bytemuck = "1.23.0"
thiserror = "2.0.12"
downcast-rs = "2.0.1"
crossbeam-queue = "0.3.2"
chrono = { version = "0.4.41", features = ["serde"] }

mesocarp = "0.12.1"


[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
aika = { path = "." }

[[bench]]
name = "hlocal"
harness = false
path = "benches/hlocal_overhead.rs"

[[bench]]
name = "st"
harness = false
path = "benches/st_overhead.rs"
