//! Agent traits and execution contexts for both single-threaded and multi-threaded simulations.
//! Provides `Agent` trait for single-threaded worlds and `ThreadedAgent` for multi-threaded planets,
//! along with their respective context structures that manage state and inter-agent communication.

use bytemuck::{Pod, Zeroable};
use mesocarp::{
    logging::journal::Journal,
};

use crate::{
    objects::{AntiMsg, Event, Mail, Msg, Transfer},
    AikaError,
};

/// Shared context local `ThreadedAgents` mutate within a `Planet` thread
pub struct PlanetContext<const INTER_SLOTS: usize, MessageType: Pod + Zeroable + Clone> {
    /// state of each `ThreadedAgent` on the `Planet`
    pub agent_states: Vec<Journal>,
    /// `Planet` global state
    pub world_state: Journal,
    /// current time
    pub time: u64,
    /// world ID in the interplanetary messaging system
    pub world_id: usize,
    /// interplanetary messaging system user interface
    /// all anti messages generated by this `Planet`
    pub anti_msgs: Journal,
    /// send counter for current time stamp
    pub(crate) sends: Vec<Mail<MessageType>>,
}

impl<const INTER_SLOTS: usize, MessageType: Pod + Zeroable + Clone>
    PlanetContext<INTER_SLOTS, MessageType>
{
    /// Spawn a new context environment for a `Planet`.
    pub fn new(
        world_arena_size: usize,
        anti_msg_arena_size: usize,
        world_id: usize,
    ) -> Self {
        Self {
            agent_states: Vec::new(),
            world_state: Journal::init(world_arena_size),
            time: 0,
            world_id,
            anti_msgs: Journal::init(anti_msg_arena_size),
            sends: Vec::new(),
        }
    }

    /// Initialize a `ThreadedAgent`'s state `Journal`.
    pub fn init_agent_contexts(&mut self, state_arena_size: usize) {
        self.agent_states.push(Journal::init(state_arena_size));
    }
    /// Send a `Msg` to another `Planet`
    pub fn send_mail(&mut self, msg: Msg<MessageType>, to_world: usize) -> Result<(), AikaError> {
        if msg.recv < self.time {
            return Err(AikaError::TimeTravel);
        }
        let anti = AntiMsg::new(msg.sent, msg.recv, msg.from, msg.to);
        let outgoing = Mail::write_letter(Transfer::Msg(msg), self.world_id, Some(to_world));
        self.sends.push(outgoing);
        let stays: Mail<MessageType> =
            Mail::write_letter(Transfer::AntiMsg(anti), self.world_id, Some(to_world));
        self.anti_msgs.write(stays, self.time, None);
        Ok(())
    }
}

/// A `ThreadedAgent` is an independent logical process that belongs to a `Planet` and can schedule events,
/// send messages, and interact with that `Planet`'s `PlanetContext`.
pub trait ThreadedAgent<const SLOTS: usize, MessageType: Pod + Zeroable + Clone> {
    fn step(&mut self, context: &mut PlanetContext<SLOTS, MessageType>, agent_id: usize) -> Event;
    fn read_message(
        &mut self,
        context: &mut PlanetContext<SLOTS, MessageType>,
        msg: Msg<MessageType>,
        agent_id: usize,
    );
}
