//! Agent traits and execution contexts for both single-threaded and multi-threaded simulations.
//! Provides `Agent` trait for single-threaded clusters and `ThreadedAgent` for multi-threaded planets,
//! along with their respective context structures that manage state and inter-agent communication.
use bytemuck::{Pod, Zeroable};
use mesocarp::logging::journal::Journal;

use crate::{
    env::Environment,
    objects::{AntiMsg, Event, Mail, Msg, Transfer},
    AikaError,
};

/// Shared context local `ThreadedAgents` mutate within a `Planet` thread
pub struct Context<MessageType: Pod + Zeroable + Clone> {
    /// state of each `ThreadedAgent` on the `Planet`
    pub env: Box<dyn Environment>,
    /// current time
    pub time: u64,
    /// termination time of the cluster.
    pub terminal: u64,
    /// cluster ID in the inter-cluster messaging system.
    pub cluster_id: usize,
    /// connection indicator
    pub connected: bool,
    /// all anti-messages generated by this `Planet`
    pub anti_msgs: Journal,
    /// sends for this time stamp.
    pub(crate) outbox: Vec<Mail<MessageType>>,
}

impl<MessageType: Pod + Zeroable + Clone> Context<MessageType> {
    /// Spawn a new context environment for a `Planet`.
    pub fn new(
        env: impl Environment + 'static,
        connected: bool,
        cluster_id: usize,
        terminal: u64,
    ) -> Self {
        let env = Box::new(env);
        Self {
            env,
            time: 0,
            cluster_id,
            connected,
            anti_msgs: Journal::init(8 * 1024),
            outbox: Vec::new(),
            terminal,
        }
    }

    /// Send a `Msg` to another `Planet`
    pub fn send_mail(&mut self, msg: Msg<MessageType>, to_cluster: usize) -> Result<(), AikaError> {
        if msg.recv > self.terminal {
            return Ok(());
        }
        if msg.recv < self.time {
            return Err(AikaError::TimeTravel);
        }
        if self.connected {
            let anti = AntiMsg::new(msg.sent, msg.recv, msg.from, msg.to);
            let stays: Mail<MessageType> =
                Mail::write_letter(Transfer::AntiMsg(anti), self.cluster_id, Some(to_cluster));
            self.anti_msgs.write(stays, self.time, None);
        }
        let outgoing = Mail::write_letter(Transfer::Msg(msg), self.cluster_id, Some(to_cluster));
        self.outbox.push(outgoing);
        Ok(())
    }
}

pub trait Actor<MessageType: Clone + Pod + Zeroable> {
    fn step(&mut self, env: &mut Context<MessageType>, actor_id: usize)
        -> Result<Event, AikaError>;
}

/// A `ThreadedAgent` is an independent logical process that belongs to a `Planet` and can schedule events,
/// send messages, and interact with that `Planet`'s `PlanetContext`.
pub trait ConnectedActor<MessageType: Pod + Zeroable + Clone>: Actor<MessageType> {
    fn read_message(
        &mut self,
        env: &mut Context<MessageType>,
        msg: Msg<MessageType>,
        actor_id: usize,
    );
}
